name: 'Send Android Release to Telegram'
description: 'Send APK or AAB files to a Telegram chat/channel'
author: 'Nebiyu Elias'
inputs:
  keystore_base64:
    description: "Base64-encoded Android keystore"
    required: true
  keystore_password:
    description: "Keystore password"
    required: true
  key_alias:
    description: "Alias of the key"
    required: true
  key_password:
    description: "Password for the key"
    required: true
  chat_id:
    description: "Telegram chat ID"
    required: true
  bot_token:
    description: "Telegram Bot API Token"
    required: true
  message:
    description: "Message to send"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'send'
  color: 'blue'
